[build]
  base = "jobapp1" # Set the base directory to the directory containing your source code and package.json
  command = "npm run build" # Define the build command
  publish = "jobapp1/public" # Specify the publish directory where the built files are located
